name: phantom-unit-math
version: 0.1.0.0
homepage: https://github.com/chris-martin/phantom-unit
license: BSD3
license-file: LICENSE
author: Chris Martin
maintainer: ch.martin@gmail.com
copyright: 2017 Chris Martin
github: chris-martin/phantom-unit

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base

library:
  source-dirs: src
  exposed-modules:
    - PhantomUnit.Math
    - PhantomUnit.Math.Addition
    - PhantomUnit.Math.Exponentiation
    - PhantomUnit.Math.FromInteger
    - PhantomUnit.Math.Rounding
    - PhantomUnit.Math.ScalarDivision
    - PhantomUnit.Math.ScalarMultiplication

tests:
  test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - phantom-unit-math
