name: phantom-unit
version: 0.1.0.0
homepage: https://github.com/chris-martin/phantom-unit
license: BSD3
license-file: LICENSE
author: Chris Martin
maintainer: ch.martin@gmail.com
copyright: 2017 Chris Martin
github: chris-martin/phantom-unit

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base

library:
  source-dirs: src
  exposed-modules: Lib

tests:
  test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - phantom-unit
