name: phantom-unit-time
version: 0.1.0.0
homepage: https://github.com/chris-martin/phantom-unit
license: BSD3
license-file: LICENSE
author: Chris Martin
maintainer: ch.martin@gmail.com
copyright: 2017 Chris Martin
github: chris-martin/phantom-unit

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base
  - phantom-unit-math

library:
  source-dirs: src
  exposed-modules:
    - PhantomUnit.Time
    - PhantomUnit.Time.Duration
    - PhantomUnit.Time.FromDuration
    - PhantomUnit.Time.TimeUnit
    - PhantomUnit.Time.ToDuration
    - PhantomUnit.Time.Units
    - PhantomUnit.Time.UseCases

tests:
  test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - phantom-unit-time
